### ISSUE TITLE
Please stop opening new plugin-hub pull requests

### ISSUE THREAD

**Issue by Felanbird** [ividrine/osrs-clan-notifications#1]
Hello, I'm opening this issue in hopes you'll actually see it.

You've been asked to stop opening new pull requests in 2 of your now 6 PRs 
https://github.com/runelite/plugin-hub/pull/4354#issuecomment-1546790052 https://github.com/runelite/plugin-hub/pull/4356#issuecomment-1546794220

The reason this is happening is you keep deleting your dev branch, instead of pushing new changes. While that is a way of approaching open source development, it's extremely annoying when it comes to when you are attempting to PR to someone else's repo.
I would strongly suggest you you stop doing this, otherwise they'll likely just block you from the repo and you'll be unable to submit your plugin.

**Comment by ividrine** [comment]
I understand, I spoke with some admins on the discord server last night about this and was not aware pushing new changes would update the PR. I won't make that mistake again, and thank you for taking the time to reach out and explain that.
